INSERT INTO categories (name, created_at, updated_at) VALUES
                                                          ('Smartphones', NOW(), NOW()),
                                                          ('Laptops & Computers', NOW(), NOW()),
                                                          ('Mobile Accessories', NOW(), NOW()),
                                                          ('Audio & Headphones', NOW(), NOW()),
                                                          ('Televisions', NOW(), NOW()),
                                                          ('Home Appliances', NOW(), NOW()),
                                                          ('Kitchen Appliances', NOW(), NOW()),
                                                          ('Gaming Consoles & Accessories', NOW(), NOW()),
                                                          ('Computer Peripherals', NOW(), NOW()),
                                                          ('Networking Devices', NOW(), NOW()),
                                                          ('Wearable Technology', NOW(), NOW()),
                                                          ('Cameras & Photography', NOW(), NOW()),
                                                          ('Office Furniture', NOW(), NOW()),
                                                          ('Smart Home Devices', NOW(), NOW()),
                                                          ('Storage Devices', NOW(), NOW()),
                                                          ('Power & Charging', NOW(), NOW()),
                                                          ('Monitors & Displays', NOW(), NOW()),
                                                          ('Printers & Scanners', NOW(), NOW()),
                                                          ('Software & Licenses', NOW(), NOW()),
                                                          ('Gaming Chairs & Desks', NOW(), NOW());