/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreHomeRouteImport } from './routes/store/home'
import { Route as StoreSettingsIndexRouteImport } from './routes/store/settings/index'
import { Route as StoreSearchIndexRouteImport } from './routes/store/search/index'
import { Route as StoreProductIndexRouteImport } from './routes/store/product/index'
import { Route as StoreCartIndexRouteImport } from './routes/store/cart/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as StoreProductProductIdRouteImport } from './routes/store/product/$productId'
import { Route as AdminProductsCreateProductRouteImport } from './routes/admin/products/create-product'
import { Route as AdminCategoriesCreateCategoryRouteImport } from './routes/admin/categories/create-category'
import { Route as StoreAuthSignUpIndexRouteImport } from './routes/store/auth/sign-up/index'
import { Route as StoreAuthSignInIndexRouteImport } from './routes/store/auth/sign-in/index'
import { Route as AdminProductsEditProductIdRouteImport } from './routes/admin/products/edit/$productId'
import { Route as AdminCategoriesEditCategoryIdRouteImport } from './routes/admin/categories/edit/$categoryId'

const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StoreHomeRoute = StoreHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreSettingsIndexRoute = StoreSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreSearchIndexRoute = StoreSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreProductIndexRoute = StoreProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCartIndexRoute = StoreCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminProductsCreateProductRoute =
  AdminProductsCreateProductRouteImport.update({
    id: '/products/create-product',
    path: '/products/create-product',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCategoriesCreateCategoryRoute =
  AdminCategoriesCreateCategoryRouteImport.update({
    id: '/categories/create-category',
    path: '/categories/create-category',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const StoreAuthSignUpIndexRoute = StoreAuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreAuthSignInIndexRoute = StoreAuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminProductsEditProductIdRoute =
  AdminProductsEditProductIdRouteImport.update({
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCategoriesEditCategoryIdRoute =
  AdminCategoriesEditCategoryIdRouteImport.update({
    id: '/categories/edit/$categoryId',
    path: '/categories/edit/$categoryId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/store/home': typeof StoreHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/categories/create-category': typeof AdminCategoriesCreateCategoryRoute
  '/admin/products/create-product': typeof AdminProductsCreateProductRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/store/cart': typeof StoreCartIndexRoute
  '/store/product': typeof StoreProductIndexRoute
  '/store/search': typeof StoreSearchIndexRoute
  '/store/settings': typeof StoreSettingsIndexRoute
  '/admin/categories/edit/$categoryId': typeof AdminCategoriesEditCategoryIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/store/auth/sign-in': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up': typeof StoreAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store/home': typeof StoreHomeRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/admin/categories/create-category': typeof AdminCategoriesCreateCategoryRoute
  '/admin/products/create-product': typeof AdminProductsCreateProductRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/store/cart': typeof StoreCartIndexRoute
  '/store/product': typeof StoreProductIndexRoute
  '/store/search': typeof StoreSearchIndexRoute
  '/store/settings': typeof StoreSettingsIndexRoute
  '/admin/categories/edit/$categoryId': typeof AdminCategoriesEditCategoryIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/store/auth/sign-in': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up': typeof StoreAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/store/home': typeof StoreHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/categories/create-category': typeof AdminCategoriesCreateCategoryRoute
  '/admin/products/create-product': typeof AdminProductsCreateProductRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/store/cart/': typeof StoreCartIndexRoute
  '/store/product/': typeof StoreProductIndexRoute
  '/store/search/': typeof StoreSearchIndexRoute
  '/store/settings/': typeof StoreSettingsIndexRoute
  '/admin/categories/edit/$categoryId': typeof AdminCategoriesEditCategoryIdRoute
  '/admin/products/edit/$productId': typeof AdminProductsEditProductIdRoute
  '/store/auth/sign-in/': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up/': typeof StoreAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/store'
    | '/store/home'
    | '/admin/'
    | '/store/'
    | '/admin/categories/create-category'
    | '/admin/products/create-product'
    | '/store/product/$productId'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/store/cart'
    | '/store/product'
    | '/store/search'
    | '/store/settings'
    | '/admin/categories/edit/$categoryId'
    | '/admin/products/edit/$productId'
    | '/store/auth/sign-in'
    | '/store/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/store/home'
    | '/admin'
    | '/store'
    | '/admin/categories/create-category'
    | '/admin/products/create-product'
    | '/store/product/$productId'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/store/cart'
    | '/store/product'
    | '/store/search'
    | '/store/settings'
    | '/admin/categories/edit/$categoryId'
    | '/admin/products/edit/$productId'
    | '/store/auth/sign-in'
    | '/store/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/store'
    | '/store/home'
    | '/admin/'
    | '/store/'
    | '/admin/categories/create-category'
    | '/admin/products/create-product'
    | '/store/product/$productId'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/store/cart/'
    | '/store/product/'
    | '/store/search/'
    | '/store/settings/'
    | '/admin/categories/edit/$categoryId'
    | '/admin/products/edit/$productId'
    | '/store/auth/sign-in/'
    | '/store/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/store/home': {
      id: '/store/home'
      path: '/home'
      fullPath: '/store/home'
      preLoaderRoute: typeof StoreHomeRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/settings/': {
      id: '/store/settings/'
      path: '/settings'
      fullPath: '/store/settings'
      preLoaderRoute: typeof StoreSettingsIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/search/': {
      id: '/store/search/'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/product/': {
      id: '/store/product/'
      path: '/product'
      fullPath: '/store/product'
      preLoaderRoute: typeof StoreProductIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/cart/': {
      id: '/store/cart/'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/products/create-product': {
      id: '/admin/products/create-product'
      path: '/products/create-product'
      fullPath: '/admin/products/create-product'
      preLoaderRoute: typeof AdminProductsCreateProductRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/create-category': {
      id: '/admin/categories/create-category'
      path: '/categories/create-category'
      fullPath: '/admin/categories/create-category'
      preLoaderRoute: typeof AdminCategoriesCreateCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/store/auth/sign-up/': {
      id: '/store/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/store/auth/sign-up'
      preLoaderRoute: typeof StoreAuthSignUpIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/auth/sign-in/': {
      id: '/store/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/store/auth/sign-in'
      preLoaderRoute: typeof StoreAuthSignInIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/products/edit/$productId': {
      id: '/admin/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/admin/products/edit/$productId'
      preLoaderRoute: typeof AdminProductsEditProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/edit/$categoryId': {
      id: '/admin/categories/edit/$categoryId'
      path: '/categories/edit/$categoryId'
      fullPath: '/admin/categories/edit/$categoryId'
      preLoaderRoute: typeof AdminCategoriesEditCategoryIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesCreateCategoryRoute: typeof AdminCategoriesCreateCategoryRoute
  AdminProductsCreateProductRoute: typeof AdminProductsCreateProductRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminCategoriesEditCategoryIdRoute: typeof AdminCategoriesEditCategoryIdRoute
  AdminProductsEditProductIdRoute: typeof AdminProductsEditProductIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesCreateCategoryRoute: AdminCategoriesCreateCategoryRoute,
  AdminProductsCreateProductRoute: AdminProductsCreateProductRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminCategoriesEditCategoryIdRoute: AdminCategoriesEditCategoryIdRoute,
  AdminProductsEditProductIdRoute: AdminProductsEditProductIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StoreRouteRouteChildren {
  StoreHomeRoute: typeof StoreHomeRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
  StoreCartIndexRoute: typeof StoreCartIndexRoute
  StoreProductIndexRoute: typeof StoreProductIndexRoute
  StoreSearchIndexRoute: typeof StoreSearchIndexRoute
  StoreSettingsIndexRoute: typeof StoreSettingsIndexRoute
  StoreAuthSignInIndexRoute: typeof StoreAuthSignInIndexRoute
  StoreAuthSignUpIndexRoute: typeof StoreAuthSignUpIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreHomeRoute: StoreHomeRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
  StoreCartIndexRoute: StoreCartIndexRoute,
  StoreProductIndexRoute: StoreProductIndexRoute,
  StoreSearchIndexRoute: StoreSearchIndexRoute,
  StoreSettingsIndexRoute: StoreSettingsIndexRoute,
  StoreAuthSignInIndexRoute: StoreAuthSignInIndexRoute,
  StoreAuthSignUpIndexRoute: StoreAuthSignUpIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
