/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreHomeRouteImport } from './routes/store/home'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as StoreSettingsIndexRouteImport } from './routes/store/settings/index'
import { Route as StoreSearchIndexRouteImport } from './routes/store/search/index'
import { Route as StoreProductIndexRouteImport } from './routes/store/product/index'
import { Route as StoreCartIndexRouteImport } from './routes/store/cart/index'
import { Route as StoreProductProductIdRouteImport } from './routes/store/product/$productId'
import { Route as StoreAuthSignUpIndexRouteImport } from './routes/store/auth/sign-up/index'
import { Route as StoreAuthSignInIndexRouteImport } from './routes/store/auth/sign-in/index'

const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreHomeRoute = StoreHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StoreRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSettingsIndexRoute = StoreSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreSearchIndexRoute = StoreSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreProductIndexRoute = StoreProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCartIndexRoute = StoreCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreAuthSignUpIndexRoute = StoreAuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreAuthSignInIndexRoute = StoreAuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => StoreRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store': typeof StoreRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/store/home': typeof StoreHomeRoute
  '/admin': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/store/cart': typeof StoreCartIndexRoute
  '/store/product': typeof StoreProductIndexRoute
  '/store/search': typeof StoreSearchIndexRoute
  '/store/settings': typeof StoreSettingsIndexRoute
  '/store/auth/sign-in': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up': typeof StoreAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/products': typeof AdminProductsRoute
  '/store/home': typeof StoreHomeRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/store/cart': typeof StoreCartIndexRoute
  '/store/product': typeof StoreProductIndexRoute
  '/store/search': typeof StoreSearchIndexRoute
  '/store/settings': typeof StoreSettingsIndexRoute
  '/store/auth/sign-in': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up': typeof StoreAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store': typeof StoreRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/store/home': typeof StoreHomeRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/store/cart/': typeof StoreCartIndexRoute
  '/store/product/': typeof StoreProductIndexRoute
  '/store/search/': typeof StoreSearchIndexRoute
  '/store/settings/': typeof StoreSettingsIndexRoute
  '/store/auth/sign-in/': typeof StoreAuthSignInIndexRoute
  '/store/auth/sign-up/': typeof StoreAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/store'
    | '/admin/products'
    | '/store/home'
    | '/admin'
    | '/store/'
    | '/store/product/$productId'
    | '/store/cart'
    | '/store/product'
    | '/store/search'
    | '/store/settings'
    | '/store/auth/sign-in'
    | '/store/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/products'
    | '/store/home'
    | '/admin'
    | '/store'
    | '/store/product/$productId'
    | '/store/cart'
    | '/store/product'
    | '/store/search'
    | '/store/settings'
    | '/store/auth/sign-in'
    | '/store/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/store'
    | '/admin/products'
    | '/store/home'
    | '/admin/'
    | '/store/'
    | '/store/product/$productId'
    | '/store/cart/'
    | '/store/product/'
    | '/store/search/'
    | '/store/settings/'
    | '/store/auth/sign-in/'
    | '/store/auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/home': {
      id: '/store/home'
      path: '/home'
      fullPath: '/store/home'
      preLoaderRoute: typeof StoreHomeRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/settings/': {
      id: '/store/settings/'
      path: '/settings'
      fullPath: '/store/settings'
      preLoaderRoute: typeof StoreSettingsIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/search/': {
      id: '/store/search/'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/product/': {
      id: '/store/product/'
      path: '/product'
      fullPath: '/store/product'
      preLoaderRoute: typeof StoreProductIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/cart/': {
      id: '/store/cart/'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/auth/sign-up/': {
      id: '/store/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/store/auth/sign-up'
      preLoaderRoute: typeof StoreAuthSignUpIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/auth/sign-in/': {
      id: '/store/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/store/auth/sign-in'
      preLoaderRoute: typeof StoreAuthSignInIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
  }
}

interface StoreRouteRouteChildren {
  StoreHomeRoute: typeof StoreHomeRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
  StoreCartIndexRoute: typeof StoreCartIndexRoute
  StoreProductIndexRoute: typeof StoreProductIndexRoute
  StoreSearchIndexRoute: typeof StoreSearchIndexRoute
  StoreSettingsIndexRoute: typeof StoreSettingsIndexRoute
  StoreAuthSignInIndexRoute: typeof StoreAuthSignInIndexRoute
  StoreAuthSignUpIndexRoute: typeof StoreAuthSignUpIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreHomeRoute: StoreHomeRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
  StoreCartIndexRoute: StoreCartIndexRoute,
  StoreProductIndexRoute: StoreProductIndexRoute,
  StoreSearchIndexRoute: StoreSearchIndexRoute,
  StoreSettingsIndexRoute: StoreSettingsIndexRoute,
  StoreAuthSignInIndexRoute: StoreAuthSignInIndexRoute,
  StoreAuthSignUpIndexRoute: StoreAuthSignUpIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
